version: '3.8'

services:
  tahsin-ai-backend:
    build: .
    container_name: tahsin-ai-backend
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ./models:/app/models
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tahsin-ai-frontend:
    image: nginx:alpine
    container_name: tahsin-ai-frontend
    ports:
      - "8000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tahsin-ai-backend
    restart: unless-stopped

networks:
  default:
    name: tahsin-ai-network 