[phases.setup]
nixPkgs = ["cmake", "pkg-config", "build-essential", "git", "curl", "wget"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cpu",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed successfully'"]

[start]
cmd = "python app.py" 