[phases.setup]
nixPkgs = ["git", "curl"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements_railway.txt"
]

[phases.build]
cmds = ["echo 'Railway minimal build completed'"]

[start]
cmd = "python app_railway.py" 